### PR TITLE
Fix led ON/OFF

### PR DESCRIPTION
**Pull request by onesse**
GPIO outputs were inverted for LED1 and LED2.

### CODE REVIEW

**Comment by mluis1** [comment]
The LED control for the LoRaMote is correct on the original code. If you look closely to the schematic you will notice that the LED are ON when setting 0 and OFF when setting a 1.
loramote led control

**Comment by ActilityEnergy** [comment]
All right, I understand. Sorry for this mistake. 
Another thing that bother me a lot ... Do you have the shematics of IM880A ? 
Because I saw in your code RADIO_ANT_SWITCH_RX and RADIO_ANT_SWITCH_TX but I don't really know where they are connected. I would like to ask you some questions about this but I don't have any way to contact you. Would you mind if I asked your email ? 
Thank you again for your response.

**Comment by onesse** [comment]
All right, I understand. Sorry for this mistake. 
Another thing that bother me a lot ... Do you have the shematics of IM880A ? 
Because I saw in your code RADIO_ANT_SWITCH_RX and RADIO_ANT_SWITCH_TX but I don't really know where they are connected. I would like to ask you some questions about this but I don't have any way to contact you. Would you mind if I asked your email ? 
Thank you again for your response.
(wrong account last time)

**Comment by mluis1** [comment]
The IMST IM880A schematics aren't publicly available. I guess that if you contact IMST they will send it to you but I'm not sure of this.
But, generally you don't need the module schematics. Looking at the iM880A_Datasheet that you can find in the doc directory of the repository should be enough.

Concerning the RADIO_ANT_SWITCH_ pins those are normal GPIOs available on the microcontroller and they are connected to an antenna switch chip on the module.

You may use the following mail address in order to get further support. [support_rf@semtech.com](mailto:support_rf@semtech.com)

**Pull request closed without merging**
