### PR TITLE
Patch 20

### PR DESCRIPTION
**Pull request by ConnyBusy**

### CODE REVIEW

**Comment by mluis1** [comment]
@ConnyBusy 

What is the purpose of this pull-request?
Was it intended?

**Comment by ConnyBusy** [comment]
Hi mluis1,
yes it was intended. Something went wrong during summit (0fdc974). 
See above

image
with the changes It is support to be for the feature branch not develop branch
image

**Comment by mluis1** [comment]
Hi @ConnyBusy,

Thanks for the info. 
Actually you forgot to target your pull-request to `feature/5.0.0` branch. 
I have just changed the target branch and now we see only your commit.

Concerning the commit itself.
I didn't yet fully analyzed the proposition but at first sight I guess that you are right and there is an issue. Although, I guess that the proposed fix is not fully implemented. 
Shouldn't we also update the `( macMsg->BufSize + micComputationOffset - LORAMAC_MHDR_FIELD_SIZE - LORAMAC_MIC_FIELD_SIZE )` parameter?

Have you tested your fix with different Network Servers implementing 1.1.x version of the LoRaWAN specification?

Another point: As the Crypto handling functions implementation is exactly the same in `develop` and `feature/5.0.0` branches we would prefer that you make your proposal against the develop branch.

We need some more time to fully understand the proposed change and to also verify it.

**Comment by ConnyBusy** [comment]
Hi @mluis1,
Yes I have tested the fix with a LW1.1.X server and it's working fine at least for join accept sent in response to a Join Request. I didn't propose it to the development branch because I cloned only the feature branch and was not sure if both Crypto were the same.

**Comment by mluis1** [comment]
I have provided the fix against develop branch and then updated the feature/5.0.0 branch.

**Pull request closed without merging**
