### PR TITLE
Fix some bugs in ClassC

### PR DESCRIPTION
**Pull request by rossihwang**
1.Fix some bugs in ClassC
a.In LoRaMacSetDeviceClass() after set the device class as classC, then
start the RX2 immidiately;
b.The current code classC can't initialize the RX1, because the RX2 works
in continuous mode. It should be force to sleep before initialize the RX1;
c.When RX1 timeout restart the RX2.

### CODE REVIEW

**Comment by mluis1** [comment]
Thanks for your findings but, we will not merge on main repository this Pull request as is.

The reasons for that are:
    1. You have included IAR project. We don't have IAR license so when doing new releases we can't test if everything is working. Another reason for this is that we already support 3 different development environments which induces already a lot of work at each release.
    2. In main.c files you have disabled the Duty Cycle enforcement. This is mandated by the ETSI regulations. So, by default it must be enabled on the repository. It is up to the user to disable it on his development branch for test purposes only.
    3. You have disabled the Rx1 window. Currently we don't see a reason why we should do it.

Concerning the LoRaMac.c changes we will analyze them and integrate them when necessary.
As said on the Issue #26 we are currently testing the Class C. When these tests are finished we will release a new version trying to solve all the current Class C issues.

**Comment by rossihwang** [comment]
I see！ Just hope it can help!

**Comment by mluis1** [comment]
Yes, it helps and again thanks for your findings and propositions.

**Comment by mluis1** [comment]
May I ask you which LoRaWAN server implementation are you using?

**Comment by rossihwang** [comment]
we use the service from loriot.io, is that any problem?

**Comment by mluis1** [comment]
No it isn't a problem. It is just to know, like this we can also test the Class C corrections with that server.

**Comment by rossihwang** [comment]
loriot.io can offer a community account for free, which can regist 1 gateway and 10 devices. :)

**Comment by mluis1** [comment]
Thanks, for the info.

**Pull request closed without merging**
