### PR TITLE
Update sx1272.c

### PR DESCRIPTION
**Pull request by alphaemmeo**
Fix the SNR value on RadioEvents->RxDone. It is wrongly returned the register value

### CODE REVIEW

**Comment by nestorayuso** [comment]
I think the code in the repo is fine.
you must store in SX1276.Settings.LoRaPacketHandler.SnrValue the raw snr value.

snr variable is used to calculate the rssi value only.
if snr is below zero, you need to add it (substract it) to the returned rssi raw value.

**Comment by reissjason** [comment]
There is loss of precision, truncating to dB, with this pull request.
The raw value can be converted to cB.

**Comment by alphaemmeo** [comment]
The LoRaWAN™ protocol reports:
The margin (Margin) is the demodulation signal-to-noise ratio in dB rounded to the nearest integer value for the last successfully received DevStatusReq command. It is a signed integer of 6 bits with a minimum value of -32 and a maximum value of 31.

https://lora-alliance.org/sites/default/files/2018-07/lorawan1.0.3.pdf

**Comment by reissjason** [comment]
And to accurately round to the nearest integer in dB, cB should be evaluated.

**Comment by alphaemmeo** [comment]
Ok, I could agree with you. But the same reasoning is also true for the RSSI calculation with SNR < 0. What do you think?

**Comment by mluis1** [comment]
Thanks for the proposition. I have discussed with someone from the Alliance technical committee and we come up with an agreement.

In order to clarify things the specification will be modified in order to make things less confusing.

The specification text will be changed to something like the following:
image

The proposed fix on this pull-request and #585 pull-request doesn't fully implement the correct behavior. In plus we also need to verify this behavior for SX126x radios.

We will provide a fix for this as soon as possible.

**Comment by alphaemmeo** [comment]
ok Miguel, 
if you need I can do a new pull request with the correct behavior.
thanks!

**Pull request closed without merging**
