### PR TITLE
Avoid duplicate uplink sequence numbers when receiving bad MIC or add…

### PR DESCRIPTION
**Pull request by catsup**
…ress in confirmed transmits.

If during a confirmed message transmission we receive a downlink frame with either
an address not matching ours, or an incorrect MIC, control is returned to the user
application with an error status, and the upLinkCounter is not incremented. Thus,
the next uplink frame is sent with the same sequence number, and likely discarded
by the receiving server.

The fix involves discarding the invalid downlink and continuing the retransmission
of the uplink frame until either a downlink response/ack is received, or the retry
count is reached.

### CODE REVIEW

**Comment by catsup** [comment]
Note this patch also applies to Release 3.3.

**Comment by reissjason** [comment]
Calling the rx2 timer callback will not have the correct timing. The window will be opened when the timee r expires.

**Comment by mluis1** [comment]
We will investigate the issue.

**Comment by catsup** [comment]
Hi Jason,

yes, good point - the rx isn't really needed, but it makes sure all the proper callbacks get invoked.

Regards,
Marc

**Comment by catsup** [comment]
Closing pull request, more appropriate fix on the way.

**Comment by mluis1** [comment]
May we ask you to follow the coding conventions in place.

Please use spaces instead of TAB characters.

Your modification should look like to the following:
```C
        } 
        else
        {
            /*
             * For confirmed uplinks, ignore MIC and address errors and keep retrying.
             */
            if( ( LoRaMacEventInfo.Status == LORAMAC_EVENT_INFO_STATUS_MIC_FAIL ) ||
                ( LoRaMacEventInfo.Status == LORAMAC_EVENT_INFO_STATUS_ADDRESS_FAIL ) )
            {
                AckTimeoutRetry = true;
            }
```
Instead of:
```C
        } else {
                /*
                 * For confirmed uplinks, ignore MIC and address errors and keep retrying.
                 */
                if ((LoRaMacEventInfo.Status == LORAMAC_EVENT_INFO_STATUS_MIC_FAIL) ||
                    (LoRaMacEventInfo.Status == LORAMAC_EVENT_INFO_STATUS_ADDRESS_FAIL)) {
                AckTimeoutRetry = true;
            }
```

Once we have tested this fix we will merge it.

Thanks.

**Comment by catsup** [comment]
Sure, no problem.

Thanks,
Marc

**Comment by mluis1** [comment]
Applied on V3.4.1 version.

**Pull request closed without merging**
