### PR TITLE
Update sx1272.c :: Fix the SNR value on RadioEvents->RxDone

### PR DESCRIPTION
**Pull request by alphaemmeo**
Fix the SNR value on RadioEvents->RxDone. It is wrongly returned the register value

### CODE REVIEW

**Comment by mluis1** [comment]
Thanks for the proposition. 
But, we can't accept this proposition. for 3 reasons.

1st reason is that you are proposing the fix against the master branch. We would like to have the proposals against the develop branch. Please refer to the Wiki pages [Repository-Rules-(Issues-Pull-Requests-reporting)](https://github.com/Lora-net/LoRaMac-node/wiki/Repository-Rules-(Issues-Pull-Requests-reporting))

2nd reason is that the same happens to the SX1276 driver. Thus the pull-request should also include the fix for that radio.

3rd reason is that the implementation is correct and complies to the LoRaWAN specification. Please refer to the following issues for more details:  #143, #104, #75 and #29. In case you disagree please send a change request to the LoRa-Alliance technical committee.

**Comment by alphaemmeo** [comment]
Hi,
I apologies for the point one. You are right.
For the second one I was fixing the SX1276 too, but then I read your message.
For the 3rd point I don't agree you because the our explain don't match the LoRaWAN 1.0.2 

Thanks a lot for your support.

**Comment by mluis1** [comment]
The specification hasn't changed on this subject since the 1st release.

The specification says the following:

> The demodulation margin (Margin) is an 8-bit unsigned integer in the range of 0..254 indicating the link margin in dB of the last successfully received LinkCheckReq command.  A value of “0” means that the frame was received at the demodulation floor (0 dB or no margin) while a value of “20”, for example, means that the frame reached the gateway 20 dB above the demodulation floor. Value “255” is reserved.

The value that the specification is expecting is the radio register raw value which corresponds to the demodulation margin.

Again, if you are unhappy with the situation Please contact the LoRa-Alliance technical committee in order to have this changed in the specification. 

Until it changes in the specification we can't change the code.

**Comment by alphaemmeo** [comment]
The protocol fragment you reported concerns the LinkCheckAns message. 
This message is sent by the LoRa Network Server. In this case the margin value is not read by the sx127x chip but directly by the LoRaMAC command payload.

The SNR read by the chip is used in the DevStatusAns (from Sensor to Network Server) where the LoRaWAN 1.0.x says:

> The margin (Margin) is the demodulation signal-to-noise ratio in dB rounded to the nearest integer value for the last successfully received DevStatusReq command. It is a signed integer of 6 bits with a minimum value of -32 and a maximum value of 31.


Thanks for you feedback.

**Comment by mluis1** [comment]
Yes, you are right. My mistake.
 
But, the answer is still the same. The expected value on DevStatusAns is the radio register raw value. It is a 1 to 1 copy of the values.

**Pull request closed without merging**
